services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tododb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tododb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  pgdata:
